In [69]:

for i in range(5):

    last_chain_seen = "A"
    
    offset = 1000
    out = []
    with open(f"../final/HO/HO_{i}.pdb") as f:
        for line in f.readlines():
            
            if line[:4] == "ATOM" and line[21] != "A":
                resid = int(line[22:26]) + offset
                out_line = f"{line[:21]}A{resid:4d}{line[26:]}"
                out.append(out_line)
            else:
                if line.startswith("TER") or line.startswith("END"):
                    continue

                resid = int(line[22:26])
                out_line = f"{line[:21]}A{resid:4d}{line[26:]}"
                
                out.append(out_line)
    
        out.append("TER\n")
        out.append("END\n")
                
    with open(f"HO_{i}.pdb","w") as f:
        f.writelines(out)
        

In [61]:
import pandas as pd

for i in range(5):

    df = pd.read_csv(f"../final/L/L_{i}.csv")
    df = df.drop(columns="Unnamed: 0")
    df["Mutation"] = [f"{m[0]}{int(m[1:-1])+1}{m[-1]}" for m in df["Mutation"]]
    df["pos"] = df["pos"] + 1
    
    df.to_csv(f"../final/L/L_{i}.csv",index=False)
        

In [67]:
import numpy as np

ddG = []
for i in range(5):
    df = pd.read_csv(f"../final/L/L_{i}.csv")
    ddG.append(np.array(df["ddG (kcal/mol)"]))

ddG
    

[array([ 0.1192, -0.0872,  0.1599, ..., -0.1544,  0.0168,  0.1051],
       shape=(13560,)),
 array([ 0.1408,  0.2565,  0.3458, ..., -0.1406,  0.0467,  0.134 ],
       shape=(12882,)),
 array([ 0.0916,  0.0678,  0.1767, ..., -0.1385,  0.0352,  0.1295],
       shape=(12882,)),
 array([ 0.0937,  0.1282,  0.2107, ..., -0.1611,  0.0096,  0.1044],
       shape=(12882,)),
 array([ 0.0609, -0.1215,  0.0067, ..., -0.1612,  0.0034,  0.1005],
       shape=(13560,))]